name: smnls
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit
  - keras
  - matplotlib
  - nltk
  - numpy
  - pandas
  - python=3.7
  - pytorch
  - scipy
  - seaborn
  - pip:
    - pytorch-nlp
    - tensorboardx
    - torchtext
