name: smnls
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit
  - jupyter
  - matplotlib
  - nltk
  - numpy
  - pandas
  - python=3.7
  - pytorch
  - scipy
  - seaborn
  - pip:
    - tensorboardx
    - torchtext
    - sklearn
